# target programming lamguage
language: java

# JDK versios support
jdk:
  - oraclejdk7
  - oraclejdk8
  
sudo: true

notifications:
  email: false
  
before_install:
  - apt-get update
  - apt-get install -y maven
  
# run tests, findbugs, pmd and friends using Ant, Maven or Gradle
script: gradle build
